# Generated by Django 5.0.6 on 2024-07-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_combination', models.CharField(max_length=100)),
                ('number_of_turn', models.IntegerField(default=10)),
                ('pellet_1', models.CharField(blank=True, default='1', max_length=10, null=True)),
                ('pellet_2', models.CharField(blank=True, max_length=10, null=True)),
                ('pellet_3', models.CharField(blank=True, max_length=10, null=True)),
                ('pellet_4', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
