# Generated by Django 5.0.6 on 2024-07-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_pellet_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pellet_1',
            field=models.CharField(blank=True, choices=[('\x1b[33m■', '🟨'), ('\x1b[34m■', 'bleue'), ('\x1b[31m■', 'rouge'), ('\x1b[32m■', 'vert'), ('\x1b[35m■', 'violet'), ('\x1b[39m■', 'blanc')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='pellet_2',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='pellet_3',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='pellet_4',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
