# Generated by Django 5.0.6 on 2024-07-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_pellet_1_alter_game_pellet_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pellet_1',
            field=models.CharField(blank=True, choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Orange', '🟧')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='pellet_2',
            field=models.CharField(blank=True, choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Orange', '🟧')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='pellet_3',
            field=models.CharField(blank=True, choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Orange', '🟧')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='pellet_4',
            field=models.CharField(blank=True, choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Orange', '🟧')], max_length=6, null=True),
        ),
    ]
