# Generated by Django 5.0.6 on 2024-07-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_pellet_1_alter_game_pellet_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pellet_1', models.CharField(blank=True, choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Orange', '🟧')], max_length=6, null=True)),
                ('pellet_2', models.CharField(blank=True, choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Orange', '🟧')], max_length=6, null=True)),
                ('pellet_3', models.CharField(blank=True, choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Orange', '🟧')], max_length=6, null=True)),
                ('pellet_4', models.CharField(blank=True, choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Orange', '🟧')], max_length=6, null=True)),
            ],
            options={
                'verbose_name': 'Tour',
            },
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Partie'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='pellet_1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pellet_2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pellet_3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pellet_4',
        ),
    ]
