# Generated by Django 5.0.6 on 2024-07-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_game_number_of_turn_game_number_of_turns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='turns',
        ),
        migrations.DeleteModel(
            name='Turn',
        ),
        migrations.AddField(
            model_name='game',
            name='turns',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
