# Generated by Django 5.0.6 on 2024-07-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_game_turns_delete_turn_game_turns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pellet_1', models.CharField(blank=True, choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Orange', '🟧')], max_length=6, null=True)),
                ('pellet_2', models.CharField(blank=True, choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Orange', '🟧')], max_length=6, null=True)),
                ('pellet_3', models.CharField(blank=True, choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Orange', '🟧')], max_length=6, null=True)),
                ('pellet_4', models.CharField(blank=True, choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Orange', '🟧')], max_length=6, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='turns',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.turn'),
            preserve_default=False,
        ),
    ]
