# Generated by Django 5.0.6 on 2024-07-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_turn_alter_game_turns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='turns',
        ),
        migrations.AddField(
            model_name='game',
            name='turns',
            field=models.ManyToManyField(to='game.turn'),
        ),
    ]
