# Generated by Django 5.0.6 on 2024-07-19 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_game_turns_game_turns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='turns',
        ),
        migrations.AddField(
            model_name='game',
            name='turns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.turn'),
        ),
    ]
