# Generated by Django 5.0.6 on 2024-07-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_game_turns_game_turns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turns',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
