# Generated by Django 5.0.6 on 2024-07-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_game_turns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='turns',
        ),
        migrations.AddField(
            model_name='game',
            name='win',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='turn',
            name='pellet_1',
            field=models.CharField(choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Marron', '🟫')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turn',
            name='pellet_2',
            field=models.CharField(choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Marron', '🟫')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turn',
            name='pellet_3',
            field=models.CharField(choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Marron', '🟫')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turn',
            name='pellet_4',
            field=models.CharField(choices=[('Jaune', '🟨'), ('Bleue', '🟦'), ('Rouge', '🟥'), ('Vert', '🟩'), ('Violet', '🟪'), ('Marron', '🟫')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
