# Generated by Django 5.0.6 on 2024-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_game_turns_game_win_alter_turn_pellet_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='win',
            new_name='end_game',
        ),
        migrations.AddField(
            model_name='game',
            name='msg_end_game',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
