# Generated by Django 5.0.6 on 2024-07-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_rename_win_game_end_game_game_msg_end_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turns',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
