# Generated by Django 5.0.6 on 2024-07-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_remove_game_turns'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turns',
            field=models.ManyToManyField(to='game.turn'),
        ),
    ]
