# Generated by Django 5.0.6 on 2024-07-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_game_turns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='turns',
        ),
        migrations.AddField(
            model_name='game',
            name='turns',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.turn'),
            preserve_default=False,
        ),
    ]
