# Generated by Django 5.0.6 on 2024-08-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_remove_game_turns'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
