# Generated by Django 5.0.6 on 2024-08-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_turn_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='game_id',
            field=models.IntegerField(default=1),
        ),
    ]
