# Generated by Django 5.0.6 on 2024-08-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_alter_turn_game_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='game_id',
        ),
    ]
