# Generated by Django 5.0.6 on 2024-08-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_remove_turn_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='game_id',
            field=models.IntegerField(default=1),
        ),
    ]
