# Generated by Django 5.0.6 on 2024-08-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_remove_turn_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turns',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
